### ISSUE TITLE
Getting Force close on kitkat

### ISSUE THREAD

**Issue by sajorahasan** [Hamadakram/Sneaker#3]
Hello I'm getting force on Kitkat Api 16 on genymotion while it is working fine on Android 7.1.2 API25, can you please look into it and can you bring down minimum api sdk level to atleast 16.

`java.lang.NoSuchMethodError: android.widget.LinearLayout.setElevation
                                                                            at com.irozon.sneaker.Sneaker.sneakView(Sneaker.java:360)
                                                                            at com.irozon.sneaker.Sneaker.sneakError(Sneaker.java:326)
                                                                            at com.ingridtech.ommahajan.ui.fragment.LoginFragment.onClick(LoginFragment.java:169)
                                                                            at android.view.View.performClick(View.java:4438)
                                                                            at android.view.View$PerformClick.run(View.java:18422)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                            at dalvik.system.NativeStart.main(Native Method)`

**Comment by c2digital** [comment]
Confirmed. Same error when testing on a Samsung G3 Mini when using the following code:-

`            Sneaker.with(this)
                    .setMessage("Searching...", R.color.white)
                    .setHeight(ViewGroup.LayoutParams.WRAP_CONTENT)
                    .sneak(R.color.st_blue);`

Android: 4.1.2
Sneaker Version: 1.0.0

**Comment by Hamadakram** [comment]
Thank you for reporting. This issue is fixed in Sneaker version 1.0.1
